#ifndef __CTRLFRAME_H__
#define __CTRLFRAME_H__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "CtrlForm.h"
#include "../serial/TottoCmd.h"
#include "../GraphFrame/GraphFrame.h"

// Declare for thread support
#if !wxUSE_THREADS
#error "This sample requires thread support!"
#endif // wxUSE_THREADS

#include <wx/thread.h>
#include <wx/app.h>

WX_DEFINE_ARRAY_PTR(wxThread *, wxArrayThread);


/** Implementing MainFrame */
class CtrlFrame : public MainFrame
{
public:
	/** Constructor */
	CtrlFrame(wxWindow* parent);
	~CtrlFrame();

	bool Cancelled();

	// critical section protects access to all of the fields below
	wxCriticalSection m_critsect;

	// all the threads currently alive - as soon as the thread terminates, it's
	// removed from the array
	wxArrayThread m_threads;

	// semaphore used to wait for the threads to exit, see MyFrame::OnQuit()
	wxSemaphore m_semAllDone;

	// indicates that we're shutting down and all threads should exit
	bool m_shuttingDown;


protected:
	// Handlers for MainFrame events.
	void comboBoxComDropDown(wxCommandEvent& event);
	void btnOpenComClick(wxCommandEvent& event);
	void btn1Click(wxCommandEvent& event);
	void btn2Click(wxCommandEvent& event);
	void btn3Click(wxCommandEvent& event);

	void OnIdle(wxIdleEvent& event);
	DECLARE_EVENT_TABLE();

private:
	void UpdateChoiceComList();
	TottoCmd _tottoCmd;

	MeasureData *mdata;
	GraphFrame *gframe;
};

#endif // __CTRLFRAME_H__
