#ifndef __MyMainFrame__
#define __MyMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "wxForm.h"
#include "Serial.h"

//// end generated include

/** Implementing MainFrame */
class MyMainFrame : public MainFrame
{
protected:
	// Handlers for MainFrame events.
	void btnOpenComClick(wxCommandEvent& event);
	void btn1Click(wxCommandEvent& event);
	void btn2Click(wxCommandEvent& event);
	void btn3Click(wxCommandEvent& event);
public:
	/** Constructor */
	MyMainFrame(wxWindow* parent);
	//// end generated class members

private:
	void ChopperCtrlPort(unsigned int ch, bool on);
	Serial _serial;

};

#endif // __MyMainFrame__
