#ifndef __MYMAINFRAME_H__
#define __MYMAINFRAME_H__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "wxForm.h"
#include "serial/TottoCmd.h"


/** Implementing MainFrame */
class MyMainFrame : public MainFrame
{
public:
	/** Constructor */
	MyMainFrame(wxWindow* parent);
	~MyMainFrame();

protected:
	// Handlers for MainFrame events.
	void comboBoxComDropDown(wxCommandEvent& event);
	void btnOpenComClick(wxCommandEvent& event);
	void btn1Click(wxCommandEvent& event);
	void btn2Click(wxCommandEvent& event);
	void btn3Click(wxCommandEvent& event);

private:
	void UpdateChoiceComList();
	TottoCmd _tottoCmd;
};

#endif // __MYMAINFRAME_H__
